-- PL/SQL Package
CREATE OR REPLACE PACKAGE MYPACKAGE AS
    FUNCTION SQUARE(NO INT) RETURN INT;
    PROCEDURE DISPLAY(NAME VARCHAR2);
END;
/

CREATE OR REPLACE PACKAGE BODY MYPACKAGE AS
    FUNCTION SQUARE(NO INT) RETURN INT
    IS
    BEGIN
        RETURN NO * NO;
    END;
    
    PROCEDURE DISPLAY(NAME VARCHAR2)
    AS
    BEGIN
        DBMS_OUTPUT.PUT_LINE('HELLO, ' || NAME);
    END;
END;
/

-- Using the package
SET SERVEROUTPUT ON
EXECUTE MYPACKAGE.DISPLAY('WELCOME');
SELECT MYPACKAGE.SQUARE(6) FROM DUAL;
