CREATE OR REPLACE PACKAGE MYPACKAGE AS
    FUNCTION SQUARE(NO NUMBER) RETURN NUMBER;
    PROCEDURE DISPLAY(NAME VARCHAR2);
END;
/

CREATE OR REPLACE PACKAGE BODY MYPACKAGE AS
    FUNCTION SQUARE(NO NUMBER) RETURN NUMBER
    IS
    BEGIN
        RETURN NO * NO;
    END;
    
    PROCEDURE DISPLAY(NAME VARCHAR2)
    AS
    BEGIN
        DBMS_OUTPUT.PUT_LINE('HELLO, ' || NAME);
    END;
END;
/

SET SERVEROUTPUT ON
EXECUTE MYPACKAGE.DISPLAY('WELCOME');
SELECT MYPACKAGE.SQUARE(6) FROM DUAL;
